apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: guestbook
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ingress-address"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: guestbook-ui
          servicePort: 80
    host: argocd.curve-app-staging.com